// version.cpp — Build version (generated by CMake from git describe)
#ifndef GOGOL_GIT_VERSION
#define GOGOL_GIT_VERSION "unknown"
#endif

const char* gogol_build_version() {
    return GOGOL_GIT_VERSION;
}
